name: core-build-modules
on:
  workflow_call:
    inputs:
      module_repo:
        required: true
        type: string
      module_branch:
        required: false
        type: string

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        compiler: [clang]
    runs-on: ubuntu-20.04
    name: ${{ matrix.compiler }}
    env:
      COMPILER: ${{ matrix.compiler }}
    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'azerothcore/azerothcore-wotlk'
          ref: 'master'
          submodules: 'recursive'
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          path: 'modules/mod-buff-command'
      - name: Cache
        uses: actions/cache@v2
        with:
          path: var/ccache
          key: ccache:${{ matrix.compiler }}:${{ github.ref }}:${{ github.sha }}
          restore-keys: |
            ccache:${{ matrix.compiler }}:${{ github.ref }}
            ccache:${{ matrix.compiler }}
      - name: Configure OS
        run: source ./acore.sh install-deps
        env:
          CONTINUOUS_INTEGRATION: true
      - name: Create conf/config.sh
        run: source ./apps/ci/ci-conf-core.sh
      - name: Build
        run: source ./apps/ci/ci-compile.sh
      - name: Dry run
        run: source ./apps/ci/ci-dry-run.sh worldserver
      - name: Check startup errors
        run: source ./apps/ci/ci-error-check.sh
      - name: Run unit tests
        run: source ./apps/ci/ci-run-unit-tests.sh
Footer
© 2022 GitHub, Inc.
Footer navigation
Terms
Privacy
Security
Status
